export * from './text.component'
export * from './star.component'
export * from './dash.component'
export * from './comma.component'
export * from './ruble.component'
export * from './colon.component'
export * from './infinite.component'
export * from './text-ellipsis.component'
